# Generated by Django 4.2 on 2023-04-17 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("email", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("last_date_to_apply", models.DateField()),
                ("open_date", models.DateField()),
                ("close_date", models.DateField()),
                ("country", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("locations", models.TextField()),
                ("tags", models.TextField()),
                ("min_experience", models.IntegerField()),
                ("max_experience", models.IntegerField()),
                ("preferred_education", models.CharField(max_length=255)),
                ("mandatory_languages", models.CharField(max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=255,
                    ),
                ),
                ("job_category", models.CharField(max_length=255)),
                ("currency_type", models.CharField(max_length=255)),
                ("min_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("positions", models.IntegerField()),
                ("is_approved", models.BooleanField(default=False)),
                ("admin_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "employer",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relation.employer",
                    ),
                ),
            ],
        ),
    ]
