# Generated by Django 4.2 on 2023-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relation", "0002_remove_job_tags_job_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
